# Generated by Django 3.1.1 on 2020-09-16 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutorial_category', models.CharField(default=1, max_length=200)),
                ('Category_summary', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutorial_series', models.CharField(default=1, max_length=200)),
                ('Series_summary', models.CharField(default=1, max_length=200)),
                ('Tutorial_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tutorialcategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutorial_title', models.CharField(max_length=200)),
                ('Tutorial_content', models.TextField()),
                ('Tutorial_published', models.DateTimeField(default=datetime.datetime(2020, 9, 16, 10, 44, 10, 616982), verbose_name='date published')),
                ('Tutorial_series', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.tutorialseries', verbose_name='Series')),
            ],
        ),
    ]
