# Generated by Django 3.1.1 on 2020-09-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tutorial_title', models.CharField(max_length=200)),
                ('Tutorial_content', models.TextField()),
                ('Tutorial_published', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
