# Generated by Django 3.1.1 on 2020-09-14 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 11, 53, 21, 594112), verbose_name='date published'),
        ),
    ]
